# Generated by Django 2.1.2 on 2019-01-15 09:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Category',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_file', models.FileField(blank=True, null=True, upload_to='Organisation/CSV File/%Y/%m/%d/')),
                ('uploaded_date', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('file_name', models.CharField(blank=True, max_length=200)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'CSV File Meta Information',
            },
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Headers',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('organisation_name', models.CharField(blank=True, default='CIVIS', max_length=200, primary_key=True, serialize=False)),
                ('organisation_logo', models.ImageField(blank=True, null=True, upload_to='Organisation/Organisation Logo/%Y/%m/%d/', verbose_name='Organisation Logo')),
                ('phone_number', models.CharField(blank=True, max_length=10)),
                ('additional_details', models.TextField(blank=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='header',
            name='organisation_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Venter.Profile'),
        ),
        migrations.AddField(
            model_name='category',
            name='organisation_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Venter.Profile'),
        ),
    ]
