# Generated by Django 2.1.2 on 2019-01-08 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Venter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='User/Profile Picture/%Y/%m/%d/', verbose_name='Profile Picture')),
                ('phone_number', models.CharField(blank=True, max_length=10)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='category',
            old_name='organisation',
            new_name='organisation_name',
        ),
        migrations.RenameField(
            model_name='header',
            old_name='organisation',
            new_name='organisation_name',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='user',
        ),
    ]
