# Generated by Django 2.1.2 on 2019-01-28 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Venter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='file',
            name='file_size',
        ),
    ]
