# Generated by Django 2.1.2 on 2019-01-07 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Venter', '0002_auto_20190107_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='id',
        ),
        migrations.AlterField(
            model_name='organisation',
            name='organisation_name',
            field=models.TextField(blank=True, primary_key=True, serialize=False),
        ),
    ]
