# Generated by Django 2.1.2 on 2019-02-01 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Venter', '0002_auto_20190128_1409'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'permissions': (('can_delete_file', 'Delete csv file'), ('can_view_users', 'View users')), 'verbose_name_plural': 'CSV File Meta'},
        ),
        migrations.AlterField(
            model_name='file',
            name='csv_file',
            field=models.FileField(upload_to='{{user.organisation_name}}/CSV File/%Y/%m/%d/'),
        ),
    ]
