# Generated by Django 2.1.2 on 2019-02-01 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Venter', '0003_auto_20190201_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='csv_file',
            field=models.FileField(upload_to='{user.organisation_name}/CSV File/%Y/%m/%d/'),
        ),
    ]
