# Generated by Django 2.1.2 on 2019-01-10 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Venter', '0003_profile_organisation_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id',
        ),
        migrations.AlterField(
            model_name='category',
            name='organisation_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Venter.Profile'),
        ),
        migrations.AlterField(
            model_name='header',
            name='organisation_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Venter.Profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='organisation_name',
            field=models.TextField(blank=True, default='CIVIS', primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Organisation',
        ),
    ]
