# Generated by Django 2.1.2 on 2019-01-10 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Venter', '0004_auto_20190110_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='profile',
            name='organisation_logo',
            field=models.ImageField(blank=True, null=True, upload_to='Organisation/Organisation Logo/%Y/%m/%d/', verbose_name='Organisation Logo'),
        ),
        migrations.AlterField(
            model_name='file',
            name='csv_file',
            field=models.FileField(blank=True, null=True, upload_to='Organisation/CSV File/%Y/%m/%d/'),
        ),
    ]
