# Generated by Django 2.1.2 on 2019-02-01 10:18

import Venter.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Venter', '0005_auto_20190201_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='csv_file',
            field=models.FileField(upload_to=Venter.models.get_file_upload_path),
        ),
    ]
