# Generated by Django 2.1.2 on 2019-02-08 08:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Venter', '0007_auto_20190201_1901'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'verbose_name_plural': 'CSV File Meta'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(regex='^[6-9]\\d{9}$')]),
        ),
    ]
