# Generated by Django 2.1.2 on 2019-02-08 09:47

import Venter.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Venter', '0008_auto_20190208_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Please enter a valid phone number.', regex='^[6-9]\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=Venter.models.get_user_profile_picture_path),
        ),
    ]
