# Generated by Django 2.1.2 on 2019-02-15 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Venter', '0009_auto_20190208_1517'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'permissions': (('view_organisation_files', 'Can view organisation files'),), 'verbose_name_plural': 'CSV File Meta'},
        ),
    ]
