# Generated by Django 2.1.2 on 2019-02-15 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Venter', '0011_auto_20190215_1245'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'permissions': (('view_organisation_files', 'Can view organisation files'), ('view_self_files', 'Can view files uploaded by self')), 'verbose_name_plural': 'CSV File'},
        ),
    ]
