# Generated by Django 2.1.2 on 2019-02-18 06:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Venter', '0012_auto_20190215_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Please enter a valid phone number', regex='^[6-9]\\d{9}$')]),
        ),
    ]
