# Generated by Django 2.1.2 on 2019-03-01 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Venter', '0014_auto_20190221_1141'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'permissions': (('view_organisation_files', 'Can view organisation files'), ('view_self_files', 'Can view files uploaded by self'), ('delete_organisation_files', 'Can delete organisation files')), 'verbose_name_plural': 'File'},
        ),
    ]
