# Generated by Django 2.1.2 on 2019-03-01 04:08

import Venter.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Venter', '0015_auto_20190301_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='Venter/static/assets/img/default-avatar.png', null=True, upload_to=Venter.helpers.get_user_profile_picture_path),
        ),
    ]
